name = "ps2-nostalgia"
account_id = "8728ca18df5e8c92c53f3a996f2e1aab"

main = "./.cloudflare/worker.js"
site.bucket = "./.cloudflare/public"

build.command = "npm run build"

routes = [
	{ pattern = "ps2nostalgia.win", custom_domain = true }
]

compatibility_date = "2021-11-12"
workers_dev = true

compatibility_flags = [ "nodejs_compat" ]
